spring.application.name=Database-Service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/petquest-db
spring.datasource.username=petquest-db
spring.datasource.password=idpacs1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
